name: Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - run: uv run --python ${{ matrix.python-version }} python -m pytest